/*
 * API Title
 * OpenAPI for Todolist RESTful API
 *
 * OpenAPI spec version: 2.0
 * Contact: kanza.az.zahrawani28@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CreateOrUpdateTodolist;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.Todolist;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Delete existing todolist
     *
     * Delete existing todolist in databases
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void todolistTodolistIdDeleteTest() throws Exception {
        String todolistId = null;
        InlineResponse200 response = api.todolistTodolistIdDelete(todolistId);

        // TODO: test validations
    }
    /**
     * update existing todolist
     *
     * Update existing todolist indatabases
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void todolistTodolistIdPutTest() throws Exception {
        CreateOrUpdateTodolist body = null;
        String todolistId = null;
        Todolist response = api.todolistTodolistIdPut(body, todolistId);

        // TODO: test validations
    }
}
