/*
 * API Title
 * OpenAPI for Todolist RESTful API
 *
 * OpenAPI spec version: 2.0
 * Contact: kanza.az.zahrawani28@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.ArrayTodolist;
import io.swagger.client.model.CreateOrUpdateTodolist;
import io.swagger.client.model.Todolist;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for TodolistApi
 */
@Ignore
public class TodolistApiTest {

    private final TodolistApi api = new TodolistApi();

    /**
     * get all todolist
     *
     * get all todolist active by default
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void todolistGetTest() throws Exception {
        Boolean includeDone = null;
        String name = null;
        ArrayTodolist response = api.todolistGet(includeDone, name);

        // TODO: test validations
    }
    /**
     * Create new todolist
     *
     * Create new todolist databases
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void todolistPostTest() throws Exception {
        CreateOrUpdateTodolist body = null;
        Todolist response = api.todolistPost(body);

        // TODO: test validations
    }
}
